[{"name": "test.test_most_frequent_first.MostFrequentFirst.test_content", "status": "errored", "message": "unique() got an unexpected keyword argument 'axis'", "passed": false, "points": ["p03-03.1"], "backtrace": ["  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 601, in run\n    testMethod()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part03-e03_most_frequent_first/test/test_most_frequent_first.py\", line 38, in test_content\n    result = most_frequent_first(a, c)\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part03-e03_most_frequent_first/src/most_frequent_first.py\", line 7, in most_frequent_first\n    uniq = np.unique(a[:,c], axis = 0, return_counts=True)\n"]}, {"name": "test.test_most_frequent_first.MostFrequentFirst.test_same_rows", "status": "errored", "message": "unique() got an unexpected keyword argument 'axis'", "passed": false, "points": ["p03-03.1"], "backtrace": ["  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/juhassio/anaconda/lib/python3.6/unittest/case.py\", line 601, in run\n    testMethod()\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part03-e03_most_frequent_first/test/test_most_frequent_first.py\", line 29, in test_same_rows\n    result = most_frequent_first(a, c)\n", "  File \"/Users/juhassio/Desktop/hy-data-analysis-with-python-summer-2019/part03-e03_most_frequent_first/src/most_frequent_first.py\", line 7, in most_frequent_first\n    uniq = np.unique(a[:,c], axis = 0, return_counts=True)\n"]}]